spring:
  application:
    name: mcpwithspring-server

  ai:
    mcp:
      server:
        name: mcp-server-poc
        version: 0.1.0
        type: ASYNC
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse

server:
  port: 8080